image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20-git

services:
  - docker:20-dind

stages:
  - Initialize
  - Quality
  - Build
  - Publish
  - Deploy

include:
  - local: .gitlab/ci/variables.yml
  
  - local: .gitlab/ci/initialize.yml
  - local: .gitlab/ci/quality.yml
  
  - local: .gitlab/ci/development/build.yml
  - local: .gitlab/ci/development/publish.yml
  - local: .gitlab/ci/development/deploy.yml

  - local: .gitlab/ci/pre-production/build.yml
  - local: .gitlab/ci/pre-production/publish.yml
  - local: .gitlab/ci/pre-production/deploy.yml

  - local: .gitlab/ci/production/build.yml
  - local: .gitlab/ci/production/publish.yml
  - local: .gitlab/ci/production/deploy.yml