image: docker:19-git

services:
  - docker:19-dind

stages:
  - Initialize
  #- Quality
  - Build
  - Publish
  - Deploy

include:
  - local: .gitlab/ci/variables.yml
  
  - local: .gitlab/ci/initialize.yml
  #- local: .gitlab/ci/quality.yml
  
  - local: .gitlab/ci/development/build.yml
  - local: .gitlab/ci/development/publish.yml
  - local: .gitlab/ci/development/deploy.yml