# Image
image: node:15

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - cache/Cypress
    - node_modules

# Define Stages
stages:
  - Audit
  - Install
  - Quality
  - Lint
  - Test
  # - Build Image
  # - Publish Image
  # - Deploy

include:
  - local: .gitlab/ci/audit.yml
  - local: .gitlab/ci/install.yml
  - local: .gitlab/ci/quality.yml
  - local: .gitlab/ci/lint.yml
  - local: .gitlab/ci/test.yml

  # - local: .gitlab/ci/development/build-image.yml
  # - local: .gitlab/ci/development/publish-image.yml
  # - local: .gitlab/ci/development/deploy.yml

  # - local: .gitlab/ci/staging/build-image.yml
  # - local: .gitlab/ci/staging/publish-image.yml
  # - local: .gitlab/ci/staging/deploy.yml

  # - local: .gitlab/ci/production/build-image.yml
  # - local: .gitlab/ci/production/publish-image.yml
  # - local: .gitlab/ci/production/deploy.yml
