version: '3'

services:
  mock:
    image: roc-app-mock:dev
    container_name: roc-app-mock
    build:
      context: ./../microservice-json-mock-server
      dockerfile: Dockerfile.development
    volumes:
      - "./../microservice-json-mock-server:/app"
    ports:
      - "5500:5500"
    networks:
      - roc-app-net

networks:
  roc-app-net:
