# Node Image
FROM node:15

# A directory within the virtualized Docker environment
WORKDIR /app/client

# Copies everything over to Docker environment
COPY ./client /app/client

# Install all node_modules and remove the cache
# Build app
# Delete node_modules
# Install serve globally
RUN yarn && yarn cache clean \
  && yarn build \
  && rm -rf node_modules/ \
  && rm -rf src/ \
  && yarn global add serve

# Serve the application
CMD [ "serve", "-s", "build" ]