version: '3.8'

services:
  client_dev:
    stdin_open: true
    container_name: roc-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
