version: '3.8'

services:
  cypress:
    image: "cypress/included:6.3.0"
    container_name: e2e-cypress
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
    working_dir: /e2e
    entrypoint: "cypress run"
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json
    build: ./e2e
    depends_on: 
      - client_dev