# Node Image
FROM node:15

# A directory within the virtualized Docker environment
WORKDIR /app/client

# Copies package.json to Docker environment
COPY ./client/package.json /app/client

# Install all node packages and remove the cache
RUN yarn && yarn cache clean

# Copies everything over to Docker environment
COPY ./client /app/client
