# node image
FROM node:15-alpine

# directory within the virtualized cocker environment
WORKDIR /app

# copies package.json to Docker environment
COPY ./package.json /app

# install all node packages and remove the cache
RUN yarn && yarn cache clean

# runs the application
CMD yarn start