# node image
FROM node:18.4.0-alpine

# directory within the virtualized docker environment
WORKDIR /app

# copies all to docker environment
COPY . /app

# install all node packages and remove the cache
RUN yarn && yarn cache clean

# runs the application
CMD yarn start
