version: '3.8'

services:
  client_local:
    stdin_open: true
    container_name: roc-local
    build:
      context: ../
      dockerfile: docker/Dockerfile.local
    volumes:
      - ../:/app
      - ../node_modules:/app/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules: