context('Active alert codes', () => {
	it('Navigates with menu bar', () => {
		cy.login();

		cy.get('[data-testing-id=NAV_ITEM_ACTIVE_ALERT_CODES]').should('not.be.visible');

		cy.get('[data-testing-id=NAV_ITEM_ALERT_CONFIG]').click();

		cy.get('[data-testing-id=NAV_ITEM_ACTIVE_ALERT_CODES]').should('be.visible').click();

		cy.location('pathname').should('eq', '/active-alert-codes');
	});

	it('Navigates back from new page', () => {
		cy.login();

		cy.goToActiveAlertCodes();

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_NEW_CODE_BTN]').click();

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_NEW_CODE_BACK_LINK]').click();

		cy.location('pathname').should('equal', '/active-alert-codes');
	});

	it('Returns back if cancel button clicked', () => {
		cy.login();

		cy.goToActiveAlertCodeNew();

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_CANCEL]').click();

		cy.location('pathname').should('equal', '/active-alert-codes');
	});

	/**
	 * Testing all CRUD operations together to have more reliable results.
	 * Since there is only one environment yet and no DB seeding implemented
	 * tests ror viewing, editing and deleting can't be running in parallel.
	 *
	 */
	it('CRUD operations work for new alert code', () => {
		cy.login();

		cy.goToActiveAlertCodeNew();

		/**
		 * CREATE
		 */
		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_SYSTEM]').type('cypress-system');

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_CREATE]').should('be.disabled');

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_NODE]').type('cypress-node');

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_CREATE]').should('be.disabled');

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_DESCRIPTION]').type(
			'Automatically generated by Cypress'
		);

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_CREATE]').should('be.disabled');

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_STATUS]').click();

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_STATUS_NONE]').click();

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_STATUS]')
			.parent()
			.should('contain', 'Please choose a status.')
			.click();

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_STATUS_ACTIVE]').click();

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_STATUS]')
			.parent()
			.should('contain', 'active');

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_CREATE]').should('not.be.disabled');

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_LEVEL]').click();

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_LEVEL_WARNING]').click();

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_LEVEL]')
			.parent()
			.should('contain', 'warning');

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_CREATE]').should('not.be.disabled');

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_DESTINATION_robot-twin]').click();

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_CREATE]')
			.should('not.be.disabled')
			.click();

		cy.get('[data-testing-id=SNACKBAR_MESSAGE_SUCCESS]').should(
			'contain',
			'Alert code was successfully created.'
		);

		cy.get('[data-testing-id=ACTIVE_ALERT_CODE_PAGE]')
			.should('contain', 'cypress-system')
			.and('contain', 'cypress-node')
			.and('contain', 'Automatically generated by Cypress')
			.and('contain', 'a-cypress-system-cypress-node-');

		/**
		 * UPDATE
		 */
		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDIT_BTN]').click();

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_NOTES]').type('Cypress note...');

		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_EDITABLE_SAVE]').click();

		cy.get('[data-testing-id=SNACKBAR_MESSAGE_SUCCESS]').should(
			'contain',
			'Alert code was successfully updated.'
		);

		cy.get('[data-testing-id=ACTIVE_ALERT_CODE_PAGE]').and('contain', 'Cypress note...');

		/**
		 * READ
		 */
		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_BACK_LINK]').click();

		cy.get('[data-testing-id^=ACTIVE_ALERT_CODES_TABLE_ROW_]').last().click();

		/**
		 * DELETE
		 */
		cy.get('[data-testing-id=ACTIVE_ALERT_CODES_DELETE_BTN]').click();

		cy.get('[data-testing-id=SNACKBAR_MESSAGE_SUCCESS]').should(
			'contain',
			'Alert code was successfully deleted.'
		);
	});
});
