export enum SiteCloudConfigurationTypeEnum {
	ACCEPT_ORDERS,
	SITE_ROBOT_CONFIG,
	SITE_CONFIG,
	ORDER_ORIGINS,
	CUSTOMER_NOTIFICATION_TYPES,
	HELP_PAGES,
	ELEVATOR_VENDORS,
	PAYMENT_SETTINGS,
	CLEAN_TEST_ORDERS
}
