dev:build:
  stage: Build
  image: tiangolo/docker-with-compose
  before_script:
    - mkdir images
  script:
    - |
      yarn docker:prod \
      --tag release \
      --build-arg APP_ENV=dev \
      --build-arg REACT_APP_API_BASE_URL \
      --build-arg REACT_APP_API_VERSION \
      --build-arg REACT_APP_AUTH_BASE_URL \
      --build-arg REACT_APP_AUTH_REALM
    - docker save release > images/release.tar
  dependencies:
    - install
  artifacts:
    paths:
      - images
    expire_in: 30 minutes
  only:
    - master
    - production
